# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "dev", "main" ]
env:
  ROUTE: ./AnalogTrello/AnalogTrelloBE
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Enviromment
      run: |
        echo "OUTPUT=$GITHUB_WORKSPACE/output" >> $GITHUB_ENV
        echo "Output folder is"
        echo "$OUTPUT"
    
    - name: Develop
      if: ${{ env.DEVELOP_REF == 'refs/heads/develop'}}
      run: echo "Running develop"
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.ROUTE }}

    - name: Test
      run: dotnet test --no-build --verbosity normal      
      working-directory: ${{ env.ROUTE }}
      
    - name: Pack      
      working-directory: ${{ env.ROUTE }}
      run: dotnet publish --configuration Release --output $OUTPUT
    
    - name: Create Deliverable
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build Result
        path: ${{ env.OUTPUT }}
