name: Docker Image CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ROUTE: ./AnalogTrello/AnalogTrelloBE

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Docker
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: winststreloc
        password: ARs250902
        
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3.3.0
      with:
        file: AnalogTrello/AnalogTrelloBE/Dockerfile
        context: AnalogTrello/AnalogTrelloBE
        push: true
        tags: winststreloc/analog:latest
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
